version: '3.12'

services:

  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html

  redis:
    image: redis:latest
    restart: on-failure
    ports:
      - "6379:6379"


  db:
    image: postgres:16
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - .pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "$PASSWORD"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $USER"]
      interval: 10s
      timeout: 10s
      retries: 10

  app:
    build: .
    tty: true
    ports:
      - '8000:8000'
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env

  celery:
    build: .
    tty: true
    command: celery -A config
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app
    env_file:
      - .env

  celery-beat:
    build: .
    tty: true
    command: celery -A config beat
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app
    env_file:
      - .env

volumes:
  pg_data:
  static_volume: