events {
    worker_connections 1024;
}

http {
    server {
    listen 80;
    server_name 158.160.91.97;  # Замените на ваш домен или IP-адрес

    location / {
        proxy_pass http://127.0.0.1:8000;  # Адрес вашего бэкенда
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
}



; user www-data;
; worker_processes auto;
; pid /run/nginx.pid;
;
; events {
;     worker_connections 1024;
; }
;
; http {
;     server {
;         listen 80;
;         server_name example.com www.example.com;
;
;         root /var/www/html;
;         index index.html;
;
;         location / {
;             try_files $uri $uri/ =404;
;         }
;
;         location /images/ {
;             root /data;
;         }
;
;         location /api/ {
;             proxy_pass http://backend_server;
;         }
;     }
; }