# Generated by Django 5.1.3 on 2024-11-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Время на выполнение (в секундах)"
            ),
        ),
    ]
