# Generated by Django 5.1.3 on 2024-11-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_habit_time_to_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                auto_now=True,
                help_text="Установите время, когда необходимо выполнять привычку",
                null=True,
                verbose_name="Время",
            ),
        ),
    ]
