name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 30q05q1986q
          POSTGRES_DB: cw_8
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        env:
          DATABASE_URL: postgres://postgres:30q05q1986q@localhost:5432/cw_8
          SECRET_KEY: django-insecure-tv_5anpssvxh+q%$bn*j*h*p$0p02$#b!k((k!l&!h8u*e54wy
        run: |
          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV
          echo "SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV

      - name: Apply migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test